// test.js -- the lab's grader. Do not edit this file.
//
// Every check is tagged with the fundamental it depends on. A failing tag
// tells you which rule from the session the code is currently breaking.

let triage;
try {
  triage = await import("./triage.js");
} catch (err) {
  console.log("\n  STAGE 0 - triage.js will not load, so no checks can run.\n");
  console.log(`    ${err.name}: ${err.message}\n`);
  console.log("  Something is being used before it exists.");
  console.log("  Fix that one line, then run the tests again.\n");
  process.exit(1);
}

const {
  tickets, SUMMARY_LINE, toHours, buildHeader,
  totalHoursOpen, countEscalated, countBreaches, makeRowRenderers,
} = triage;

// --- tiny assertion runner --------------------------------------------

const GREEN = "\u001b[32m";
const RED = "\u001b[31m";
const DIM = "\u001b[2m";
const OFF = "\u001b[0m";

const show = (v) => {
  if (v === undefined) return "undefined";
  if (typeof v === "number" && Number.isNaN(v)) return "NaN";
  return JSON.stringify(v);
};

const results = [];

function check(tag, label, run, expected) {
  let got;
  try {
    got = run();
  } catch (err) {
    got = `${err.name}: ${err.message}`;
  }
  results.push({ tag, label, got, expected, ok: show(got) === show(expected) });
}

// --- checks -------------------------------------------------------------

check("SETUP", "the module loads and can format a ticket",
  () => SUMMARY_LINE, "T-1001 (P1)");

check("DECLARATIONS", "the report header uses the real title",
  () => buildHeader(tickets), "Daily Triage Report - 6 tickets");

check("TYPES", "an unreadable hours value falls back to 0",
  () => toHours("n/a"), 0);

check("COERCION", "total hours open across all tickets",
  () => totalHoursOpen(tickets), 158);

check("EQUALITY", "count of escalated tickets",
  () => countEscalated(tickets), 2);

check("SCOPE", "the first row renderer is numbered 1",
  () => makeRowRenderers(tickets)[0](), "1. T-1001 (P1)");

check("FUNCTIONS", "count of tickets past their SLA",
  () => countBreaches(tickets), 3);

// --- report -------------------------------------------------------------

console.log("");
for (const r of results) {
  if (r.ok) {
    console.log(`  ${GREEN}PASS${OFF}  [${r.tag}] ${r.label}`);
  } else {
    console.log(`  ${RED}FAIL${OFF}  [${r.tag}] ${r.label}`);
    console.log(`        ${DIM}expected:${OFF} ${show(r.expected)}`);
    console.log(`        ${DIM}actual:  ${OFF} ${show(r.got)}`);
  }
}

const failed = results.filter((r) => !r.ok);
console.log("");
if (failed.length === 0) {
  console.log(`  ${GREEN}All ${results.length} checks passing. The report is correct.${OFF}\n`);
} else {
  console.log(`  ${failed.length} of ${results.length} checks failing: ${failed.map((r) => r.tag).join(", ")}\n`);
  process.exit(1);
}
