plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.revature'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


// This needs to be swapped to the internal repo
repositories {
    mavenCentral()
}

dependencies {
    //This one is the core dependency, this is a sub-dependency of the others
    implementation("org.springframework.boot:spring-boot-starter")

    //These are the Spring Modules we will look at. Each one requires core and will bring it in transitively.
    // implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // implementation 'org.springframework.boot:spring-boot-starter-security'
    // implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    //These are the test implementations for unit testing
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    // testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    // testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    // testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    //SQLite driver
    runtimeOnly 'org.xerial:sqlite-jdbc'

    //Junit test platform
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
