// build.gradle
plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '8.3.11'
}

repositories {
    mavenCentral()
}

//dependencies {
//    implementation 'com.mysql:mysql-connector-j:26.7.0'
//}

dependencies {
    runtimeOnly 'com.mysql:mysql-connector-j:9.7.0'
}

application {
    mainClass = 'com.revature.demo.s3.S3Demo'
}