spring.application.name=logging-demo
app.message=Hello from the base file
spring.profiles.active=prod



# ---------- Web ----------
server.port=7000

# ---------- DataSource (SQLite) ----------
spring.datasource.url=jdbc:sqlite:database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# SQLite allows one writer at a time ? keep the pool small to avoid SQLITE_BUSY
spring.datasource.hikari.maximum-pool-size=1

# ---------- JPA / Hibernate ----------
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ---------- Logging ----------
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.root=INFO
logging.level.com.revature.logging.components.loggingexample=INFO
logging.level.com.revature.logging.loggingdemo=WARN
logging.level.org.springframework.web=WARN

logging.file.name=logs/application.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7